name             'ecs-haproxy-cassandra-cluster'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures ecs-haproxy-cassandra-cluster'
long_description 'Installs/Configures ecs-haproxy-cassandra-cluster'
version          '0.1.0'
